artifact_uri: file:///c:\Users\Max_G\OneDrive\IUBH\5_Semester\Model_Engeneering\Public_Transport_Forecasting\models\Tracking/905503404134756615/0ef04feb67044f579bdc07a53900ad8c/artifacts
end_time: 1697629232441
entry_point_name: ''
experiment_id: '905503404134756615'
lifecycle_stage: active
run_id: 0ef04feb67044f579bdc07a53900ad8c
run_name: Random_Forest_4
run_uuid: 0ef04feb67044f579bdc07a53900ad8c
source_name: ''
source_type: 4
source_version: ''
start_time: 1697629228595
status: 3
tags: []
user_id: Max_G
