channels:
- conda-forge
dependencies:
- python=3.10.9
- pip<=22.3.1
- pip:
  - mlflow==2.6.0
  - cloudpickle==2.2.1
  - numpy==1.26.0
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.2.1
  - scipy==1.11.3
name: mlflow-env
