artifact_location: file:///c:\Users\Max_G\OneDrive\IUBH\5_Semester\Model_Engeneering\Public_Transport_Forecasting\models\Tracking/905503404134756615
creation_time: 1697629213160
experiment_id: '905503404134756615'
last_update_time: 1697629213160
lifecycle_stage: active
name: Random_Forest_Final_with_Models
